/**
 * Curated list of world countries, territories, and major travel cities.
 * Used for destination autocomplete in the trip form.
 *
 * Crown Dependencies (Jersey, Guernsey, Isle of Man) are included and must
 * remain so that isCrownDependency() still triggers when a user selects them.
 *
 * Sorted alphabetically for readability; the search algorithm handles
 * prefix-first ordering at query time.
 */
export const DESTINATIONS: string[] = [
  // ── Crown Dependencies (0 absence days) ─────────────────────────────────
  'Guernsey',
  'Isle of Man',
  'Jersey',

  // ── Countries ────────────────────────────────────────────────────────────
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',

  // ── Major cities ─────────────────────────────────────────────────────────
  'Abu Dhabi',
  'Accra',
  'Addis Ababa',
  'Adelaide',
  'Algiers',
  'Almaty',
  'Amman',
  'Amsterdam',
  'Ankara',
  'Athens',
  'Auckland',
  'Baghdad',
  'Baku',
  'Bali',
  'Bangkok',
  'Barcelona',
  'Beirut',
  'Belgrade',
  'Berlin',
  'Bogotá',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Buenos Aires',
  'Cairo',
  'Calgary',
  'Cape Town',
  'Casablanca',
  'Chennai',
  'Chicago',
  'Colombo',
  'Copenhagen',
  'Cusco',
  'Doha',
  'Dubai',
  'Dublin',
  'Dubrovnik',
  'Düsseldorf',
  'Edinburgh',
  'Florence',
  'Frankfurt',
  'Geneva',
  'Glasgow',
  'Guangzhou',
  'Hamburg',
  'Hanoi',
  'Helsinki',
  'Ho Chi Minh City',
  'Hong Kong',
  'Honolulu',
  'Istanbul',
  'Jakarta',
  'Johannesburg',
  'Karachi',
  'Kathmandu',
  'Kraków',
  'Kuala Lumpur',
  'Kuwait City',
  'Lagos',
  'Lahore',
  'Lima',
  'Lisbon',
  'London',
  'Los Angeles',
  'Luxembourg City',
  'Madrid',
  'Malaga',
  'Manila',
  'Marrakech',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Milan',
  'Minneapolis',
  'Minsk',
  'Montreal',
  'Moscow',
  'Mumbai',
  'Munich',
  'Muscat',
  'Nairobi',
  'Naples',
  'New York',
  'Nice',
  'Osaka',
  'Oslo',
  'Ottawa',
  'Paris',
  'Perth',
  'Prague',
  'Reykjavik',
  'Riga',
  'Rio de Janeiro',
  'Riyadh',
  'Rome',
  'San Francisco',
  'San José',
  'Santiago',
  'São Paulo',
  'Sarajevo',
  'Seoul',
  'Seville',
  'Shanghai',
  'Shenzhen',
  'Singapore City',
  'Sofia',
  'Stockholm',
  'Sydney',
  'Taipei',
  'Tallinn',
  'Tashkent',
  'Tehran',
  'Tel Aviv',
  'Tokyo',
  'Toronto',
  'Tunis',
  'Valencia',
  'Vancouver',
  'Venice',
  'Vienna',
  'Vilnius',
  'Warsaw',
  'Wellington',
  'Yangon',
  'Yerevan',
  'Zagreb',
  'Zürich',

  // ── Popular holiday islands & regions ────────────────────────────────────
  'Bora Bora',
  'Canary Islands',
  'Cancún',
  'Corfu',
  'Crete',
  'Fuerteventura',
  'Gran Canaria',
  'Hawaii',
  'Ibiza',
  'Koh Samui',
  'Lanzarote',
  'Madeira',
  'Mallorca',
  'Mykonos',
  'Phuket',
  'Rhodes',
  'Santorini',
  'Tenerife',
  'Zakynthos',
]
