import Nav from '@/components/marketing/Nav';
import Footer from '@/components/marketing/Footer';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — StayRight',
};

export default function TermsOfServicePage() {
  return (
    <>
      <Nav />
      <main id="main-content" className="bg-[#F8F9FA] pt-28 pb-20 px-6 min-h-screen">
        <div className="max-w-3xl mx-auto">
          <h1 className="font-[family-name:var(--font-manrope)] font-extrabold text-[3rem] leading-[1.1] tracking-[-0.02em] text-[#191C1D] mb-4">
            Terms of Service
          </h1>
          <p className="font-[family-name:var(--font-inter)] text-sm text-[#3D4A42]/70 mb-10">Last Updated: [Date] [LEGAL REVIEW REQUIRED: Confirm effective date]</p>

          <div className="font-[family-name:var(--font-inter)] text-base text-[#3D4A42] leading-relaxed space-y-6">
            <p>Welcome to StayRight. By registering for an account, you agree to these Terms of Service. Please read them carefully.</p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">1. What the Service Is and Is Not</h2>
            <p>StayRight is a calculation and tracking tool designed to help you monitor your absences for UK visa and Indefinite Leave to Remain (ILR) purposes.</p>
            <p><strong>STAYRIGHT DOES NOT PROVIDE LEGAL ADVICE.</strong></p>
            <p>The results generated by StayRight are based entirely on the dates and data you input. We do not guarantee the accuracy of our software for determining your individual legal status. <strong>You are entirely responsible for verifying your compliance with UK Visas and Immigration (UKVI) rules.</strong> We strongly recommend consulting a qualified immigration solicitor before making any travel or application decisions.</p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">2. Acceptable Use</h2>
            <p>You must not use StayRight in any way that causes, or may cause, damage to the platform or impairment of its availability. You agree not to input fraudulent or maliciously false data. You must not attempt to reverse engineer the calculation engine or scrape our platform.</p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">3. Account Registration and Security</h2>
            <p>You are responsible for keeping your login credentials secure. You must notify us immediately if you suspect unauthorised access to your account. We reserve the right to suspend or terminate accounts that breach our security or acceptable use policies.</p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">4. Subscriptions and Billing</h2>
            <p>StayRight offers a Free tier and a Pro tier (which scales by monthly, annual, or lifetime options).</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Free Tier Limitations:</strong> Specific feature limits apply as detailed on our pricing page.</li>
              <li><strong>Billing:</strong> All subscription payments are processed securely by our partner, Stripe. By upgrading to Pro, you authorise us to charge the payment method on file on a recurring basis (except for lifetime purchases).</li>
            </ul>

            <h3 className="text-lg font-semibold text-[#191C1D] mt-8 mb-3 font-[family-name:var(--font-manrope)]">4.1 Cancellation and Refunds</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Monthly Subscriptions:</strong> You can cancel at any time. Your access to Pro features will continue until the end of your current billing period. No partial refunds are provided.</li>
              <li><strong>Annual Subscriptions:</strong> You can cancel at any time. We do not issue refunds for unused months once the cooling-off period has expired.</li>
              <li><strong>Lifetime Access:</strong> This is a one-off payment. No refunds are available after the cooling-off period.</li>
            </ul>

            <h3 className="text-lg font-semibold text-[#191C1D] mt-8 mb-3 font-[family-name:var(--font-manrope)]">4.2 Your 14-Day Cooling-Off Right (UK Consumers)</h3>
            <p>Under the Consumer Contracts Regulations 2013 and Consumer Rights Act 2015, you have the right to change your mind and cancel your paid subscription within <strong>14 days</strong> of your initial purchase for a full refund. If you wish to exercise this right, please contact us at [Contact Email].</p>
            <p className="text-sm text-[#006948] bg-[#006948]/10 p-4 rounded-xl border border-[#006948]/20">
              [LEGAL REVIEW REQUIRED: Ensure the checkout flow clearly acknowledges that starting the digital service immediately means the user waives the right to a refund for the prorated time used, or ensure you are happy to provide a full 14-day unconditional refund if requested.]
            </p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">5. Intellectual Property</h2>
            <p>All intellectual property rights in StayRight (including our calculation algorithms, design, logo, and copy) belong to us. You may use the software for its intended personal purpose, but you may not copy, modify, or distribute any part of it without our permission.</p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">6. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, StayRight and its creators shall not be liable for any indirect, special, or consequential loss arising from your use of the service.</p>
            <p><strong>Crucially, we explicitly exclude any liability for the outcome of your visa or ILR applications. If your application is rejected by UKVI, StayRight accepts no responsibility or financial liability.</strong></p>
            <p>In all other matters, our total liability to you shall be capped at the total amount you paid to us for the service in the <strong>12 months</strong> preceding the claim.</p>
            <p className="text-sm text-[#006948] bg-[#006948]/10 p-4 rounded-xl border border-[#006948]/20">
              [LEGAL REVIEW REQUIRED: A solicitor should review this limitation clause to ensure it is robust under English consumer protection laws, particularly regarding the exclusion of liability for application outcomes.]
            </p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">7. Governing Law</h2>
            <p>These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes relating to these Terms will be subject to the exclusive jurisdiction of the courts of England and Wales.</p>

            <h2 className="font-[family-name:var(--font-manrope)] font-bold text-2xl text-[#191C1D] mt-10 mb-4">8. Changes to These Terms</h2>
            <p>We may revise these terms to reflect changes to our services or the law. We will inform you of major changes. By continuing to use StayRight after changes are introduced, you accept the revised terms.</p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
