// Generated by Supabase CLI — re-run to refresh:
//   npm run gen:types
//
// NOTE: `plan` and `status` on `subscriptions` are typed as union literals
// here for type safety. The CLI generator outputs `string` because Postgres
// CHECK constraints don't map to TypeScript unions; we add them back manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.4'
  }
  public: {
    Tables: {
      profiles: {
        Row: {
          created_at: string
          full_name: string | null
          id: string
          notifications_120_day: boolean
          notifications_150_day: boolean
          notifications_ilr_reminder: boolean
          notifications_monthly: boolean
          notifications_return_reminder: boolean
          onboarding_completed: boolean
          updated_at: string
          visa_route: string
          visa_start_date: string | null
        }
        Insert: {
          created_at?: string
          full_name?: string | null
          id: string
          notifications_120_day?: boolean
          notifications_150_day?: boolean
          notifications_ilr_reminder?: boolean
          notifications_monthly?: boolean
          notifications_return_reminder?: boolean
          onboarding_completed?: boolean
          updated_at?: string
          visa_route?: string
          visa_start_date?: string | null
        }
        Update: {
          created_at?: string
          full_name?: string | null
          id?: string
          notifications_120_day?: boolean
          notifications_150_day?: boolean
          notifications_ilr_reminder?: boolean
          notifications_monthly?: boolean
          notifications_return_reminder?: boolean
          onboarding_completed?: boolean
          updated_at?: string
          visa_route?: string
          visa_start_date?: string | null
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          id: string
          plan: 'free' | 'pro_monthly' | 'pro_annual' | 'pro_lifetime'
          status: 'active' | 'canceled' | 'past_due' | 'unpaid'
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          id?: string
          plan?: 'free' | 'pro_monthly' | 'pro_annual' | 'pro_lifetime'
          status?: 'active' | 'canceled' | 'past_due' | 'unpaid'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          id?: string
          plan?: 'free' | 'pro_monthly' | 'pro_annual' | 'pro_lifetime'
          status?: 'active' | 'canceled' | 'past_due' | 'unpaid'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      trips: {
        Row: {
          created_at: string
          departure_date: string
          destination: string
          id: string
          notes: string | null
          return_date: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          departure_date: string
          destination: string
          id?: string
          notes?: string | null
          return_date?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          departure_date?: string
          destination?: string
          id?: string
          notes?: string | null
          return_date?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

// Standard Supabase helper generics
type PublicSchema = Database['public']

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema['Tables'] & PublicSchema['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema['Tables'] &
        PublicSchema['Views'])
    ? (PublicSchema['Tables'] &
        PublicSchema['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

// Convenience row types
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Trip = Database['public']['Tables']['trips']['Row']
export type Subscription = Database['public']['Tables']['subscriptions']['Row']
export type TripInsert = Database['public']['Tables']['trips']['Insert']
export type TripUpdate = Database['public']['Tables']['trips']['Update']
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update']

// Subscription plan and status as union literals
export type SubscriptionPlan = 'free' | 'pro_monthly' | 'pro_annual' | 'pro_lifetime'
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'unpaid'
